### ISSUE TITLE
Once I check an option, it unchecks a couple of minutes after

### ISSUE THREAD

**Issue by evonomads** [TanvirHasan19/dokan-kits#1]
I installed the plugin correctly, but every time I choose an option, it is overridden a few minutes later. For example, I check the option for only one shipping cost and it works once on the live website, but a few minutes later it shows again several shipping costs for each seller. Also, every time I go to the plugin configuration page all the options appear unchecked

**Comment by TanvirHasan19** [comment]
Hello @evonomads, I'm pleased to inform you that the issue you reported has been addressed in the latest release. Kindly download Dokan Kits v1.0.1 and let me know if you encounter any further issues as described. Thank you!

**Comment by TanvirHasan19** [comment]
Hi @evonomads,

As you haven't responded for a while. I am marking this issue as resolved. If you have any further issues feel free to create another issue.

Thanks!
